### ISSUE TITLE
Raspberry 11 (bullseye)

### ISSUE THREAD

**Issue by toteph42** [Excogitatoris69/AufnahmesteuerungTvHeadend#2]
Hi,
I upgraded my Rasperry to bullseys and installed tvheadend 4.3-1994-gc7b713edb~bullseye and your latest binares (AufnahmesteuerungTvHeadendClient. Release:1.2.1.0, TvHeadendLibrary-Release:1.2 , Juli 2022). Unfortunately I cannot use your program - it always end with `Invalid Requestdata: Wrong Username or password.`

I checked it by using a cmd.exe and executing program with proper userid and password. Login via web is possible.

Any suggestion?

**Comment by toteph42** [comment]
Hi,
found what to do: `Authentication type: Both plain and digest`

**Comment by Excogitatoris69** [comment]
Sorry for my late reply: Thanks for posting the solution.
More information can be found in the documentation on pages 23-24 (unfortunately not in English yet).
